### ISSUE TITLE
[CI/CD]: setup github actions

### ISSUE THREAD

**Issue by sub1120** [lmsGenie/lms-app#36]
### Summary

NA

### Answer following questions?

1. Is your feature related to FrontEnd? No
2. Is your feature related to Backend? No
3. Is your feature related to API Integration? No
4. Is your feature realted to CI/CD? Yes

**Comment by sub1120** [comment]
While running 

```
nx format:check
```

I am getting following error `Cannot find module '/home/subham/data/project/lms-genie/node_modules/prettier/bin-prettier'`

Full Error Details:-

```
subham@subham-Lenovo-ideapad-330-15IKB:~/data/project/lms-genie$ nx format:check
nx format:check

Check for un-formatted files

Run command using --base=[SHA1] (affected by the committed, uncommitted and untracked changes):
  --base  Base of the current branch (usually main)                                                                                         [string]

or using --base=[SHA1] --head=[SHA2] (affected by the committed changes):
  --base  Base of the current branch (usually main)                                                                                         [string]
  --head  Latest commit of the current branch (usually HEAD)                                                                                [string]

or using:
  --files        Change the way Nx is calculating the affected command by providing directly changed files, list of files delimited by commas or
                 spaces                                                                                                                     [string]
  --uncommitted  Uncommitted changes                                                                                                       [boolean]
  --untracked    Untracked changes                                                                                                         [boolean]

Options:
  --help           Show help                                                                                                               [boolean]
  --version        Show version number                                                                                                     [boolean]
  --exclude        Exclude certain projects from being processed                                                                            [string]
  --libs-and-apps  Format only libraries and applications files.                                                                           [boolean]
  --projects       Projects to format (comma/space delimited)                                                                               [string]
  --all            Format all projects                                                                                                     [boolean]

Find more information and examples at https://nx.dev/nx/format-check

Error: Cannot find module '/home/subham/data/project/lms-genie/node_modules/prettier/bin-prettier'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1096:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1089:15)
    at resolveExports (node:internal/modules/cjs/loader:565:14)
    at Module._findPath (node:internal/modules/cjs/loader:634:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
    at Function.resolve (/home/subham/data/project/lms-genie/node_modules/.pnpm/v8-compile-cache@2.3.0/node_modules/v8-compile-cache/v8-compile-cache.js:164:23)
    at Object.<anonymous> (/home/subham/data/project/lms-genie/node_modules/.pnpm/nx@16.7.3_@swc+core@1.3.51/node_modules/nx/src/command-line/format/format.js:18:31)
    at Module._compile (/home/subham/data/project/lms-genie/node_modules/.pnpm/v8-compile-cache@2.3.0/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/subham/data/project/lms-genie/node_modules/prettier/package.json'
}
```


@shivamvijaywargi,

Is this command `nx format:check` working fine at you end? 
If not, do you have any idea how to fix it?

**Comment by shivamvijaywargi** [comment]
I will check in some time.

**Comment by shivamvijaywargi** [comment]
Please use `pnpm format` to check and `pnpm format:fix` to apply prettier fixes

https://github.com/nrwl/nx/issues/16121: The issue is from the NX team, here is an open issue in their repo.
