### ISSUE TITLE
[BUG]: cloudinary images not loading in production

### ISSUE THREAD

**Issue by lmsgenie-admin** [lmsGenie/lms-app#92]
**Describe the bug**
Cloudinary Images not loading in production - https://lmsgenie-client.onrender.com/

Chrome Dev Tool
![image](https://github.com/lmsGenie/client/assets/149229872/f5c437fd-133e-4fa5-8df4-34195d552927)

Server Logs
```
Nov 11 11:53:47 PM  TypeError: fetch failed
Nov 11 11:53:47 PM      at Object.fetch (node:internal/deps/undici/undici:11576:11)
Nov 11 11:53:47 PM      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Nov 11 11:53:47 PM      at async invokeRequest (/opt/render/project/src/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.11_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
Nov 11 11:53:47 PM      at async invokeRender (/opt/render/project/src/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.11_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:254:29)
Nov 11 11:53:47 PM      at async handleRequest (/opt/render/project/src/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.11_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:447:24)
Nov 11 11:53:47 PM      at async requestHandler (/opt/render/project/src/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.11_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:464:13)
Nov 11 11:53:47 PM      at async Server.<anonymous> (/opt/render/project/src/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.11_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/start-server.js:117:13) {
Nov 11 11:53:47 PM    cause: Error: connect ECONNREFUSED ::1:37377
Nov 11 11:53:47 PM        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1574:16) {
Nov 11 11:53:47 PM      errno: -111,
Nov 11 11:53:47 PM      code: 'ECONNREFUSED',
Nov 11 11:53:47 PM      syscall: 'connect',
Nov 11 11:53:47 PM      address: '::1',
Nov 11 11:53:47 PM      port: 37377
Nov 11 11:53:47 PM    }
Nov 11 11:53:47 PM  }
Nov 11 11:53:47 PM  TypeError: fetch failed
Nov 11 11:53:47 PM      at Object.fetch (node:internal/deps/undici/undici:11576:11)
Nov 11 11:53:47 PM      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Nov 11 11:53:47 PM      at async invokeRequest (/opt/render/project/src/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.11_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
Nov 11 11:53:47 PM      at async invokeRender (/opt/render/project/src/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.11_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:254:29)
Nov 11 11:53:47 PM      at async handleRequest (/opt/render/project/src/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.11_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:447:24)
Nov 11 11:53:47 PM      at async requestHandler (/opt/render/project/src/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.11_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:464:13)
Nov 11 11:53:47 PM      at async Server.<anonymous> (/opt/render/project/src/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.11_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/start-server.js:117:13) {
Nov 11 11:53:47 PM    cause: Error: connect ECONNREFUSED ::1:37377
Nov 11 11:53:47 PM        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1574:16) {
Nov 11 11:53:47 PM      errno: -111,
Nov 11 11:53:47 PM      code: 'ECONNREFUSED',
Nov 11 11:53:47 PM      syscall: 'connect',
Nov 11 11:53:47 PM      address: '::1',
Nov 11 11:53:47 PM      port: 37377
Nov 11 11:53:47 PM    }
Nov 11 11:53:47 PM  }
Nov 11 11:53:47 PM  TypeError: fetch failed
Nov 11 11:53:47 PM      at Object.fetch (node:internal/deps/undici/undici:11576:11)
Nov 11 11:53:47 PM      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Nov 11 11:53:47 PM      at async invokeRequest (/opt/render/project/src/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.11_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
Nov 11 11:53:47 PM      at async invokeRender (/opt/render/project/src/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.11_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:254:29)
Nov 11 11:53:47 PM      at async requestHandler (/opt/render/project/src/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.11_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:475:24)
Nov 11 11:53:47 PM      at async Server.<anonymous> (/opt/render/project/src/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.11_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/start-server.js:117:13) {
Nov 11 11:53:47 PM    cause: Error: connect ECONNREFUSED ::1:37377
Nov 11 11:53:47 PM        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1574:16) {
Nov 11 11:53:47 PM      errno: -111,
Nov 11 11:53:47 PM      code: 'ECONNREFUSED',
Nov 11 11:53:47 PM      syscall: 'connect',
Nov 11 11:53:47 PM      address: '::1',
Nov 11 11:53:47 PM      port: 37377
Nov 11 11:53:47 PM    }
Nov 11 11:53:47 PM  }
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sub1120** [comment]
After adding package `sharp`, it seems intermittent an issue.

![image](https://github.com/lmsGenie/client/assets/43786036/6e54f8a9-80d3-461a-b895-d97968489e34)

**Comment by lmsgenie-admin** [comment]
It looks cache issue. Now all images are loading fine. 

![image](https://github.com/lmsGenie/client/assets/149229872/4b9aba48-be62-4e7a-876f-0d088da26382)
